services:
  api:
    build: .
    image: netvalidate:latest
    container_name: netvalidate-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Overrides forzados que no quieres que vengan del .env
      NETVALIDATE_DB_URL: sqlite+aiosqlite:////app/data/netvalidate.db
      NETVALIDATE_PROFILES_DIR: /app/examples/profiles
    volumes:
      - ./data:/app/data
      - ./examples/profiles:/app/examples/profiles:ro
    restart: unless-stopped